#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(RGB_TOG, KC_PSLS, KC_PAST, KC_PMNS, KC_P7, KC_P8, KC_P9, KC_PLUS, KC_P4, KC_P5, KC_P6, KC_PCMM, KC_P1, KC_P2, KC_P3, KC_PEQL, TG(1), KC_DOT, KC_P0, KC_PENT),
	[1] = LAYOUT(KC_NLCK, KC_NO, KC_NO, KC_CALC, KC_NO, KC_NO, KC_NO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_TRNS, KC_TAB, KC_NO, LGUI(KC_TAB))
};
